In [2]:
import numpy as np
import pandas as pd
import scipy
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse
from scipy import spatial
from scipy.spatial.distance import squareform, pdist, cdist

u_pref = pd.DataFrame({'id': ['usr_pref'],
                               'z1':  [0],
                               'z2':  [1],
                               'z3':  [1],
                               'z4':  [1],
                               'z5':  [0],
                               'z6':  [0],
                               'z7':  [0],
                               'z8':  [1],
                               'z9':  [1],
                               'z10': [1],
                               'z11': [1], 
                               'z12': [1]})

user_recipes = pd.DataFrame({'id': ['ur1', 'ur2', 'ur3', 'ur4', 'ur5', 'ur6'],
                               'z1':  [0, 0, 0, 0, 0, 0],
                               'z2':  [0, 1, 1, 1, 1, 0],
                               'z3':  [1, 1, 1, 1, 1, 1],
                               'z4':  [1, 0, 0, 0, 0, 0],
                               'z5':  [0, 1, 1, 1, 1, 1],
                               'z6':  [0, 1, 1, 1, 1, 0],
                               'z7':  [0, 0, 0, 0, 0, 0],
                               'z8':  [0, 0, 0, 0, 0, 1],
                               'z9':  [0, 0, 0, 1, 0, 0],
                               'z10': [1, 0, 0, 0, 0, 1],
                               'z11': [1, 0, 0, 0, 0, 0], 
                               'z12': [0, 0, 1, 0, 0, 0]})


recipe_db = pd.DataFrame({'id': ['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10'],
                               'z1':  [0, 1, 0, 0, 0, 1, 1, 0, 0, 0],
                               'z2':  [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
                               'z3':  [1, 1, 0, 1, 1, 1, 0, 1, 0, 1],
                               'z4':  [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
                               'z5':  [0, 1, 1, 0, 1, 0, 0, 0, 1, 1],
                               'z6':  [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                               'z7':  [0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
                               'z8':  [0, 0, 1, 0, 0, 1, 0, 0, 0, 1],
                               'z9':  [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
                               'z10': [1, 0, 0, 0, 1, 1, 0, 0, 1, 1],
                               'z11': [1, 0, 0, 1, 0, 0, 1, 0, 0, 0], 
                               'z12': [0, 1, 1, 0, 0, 1, 0, 1, 0, 1]})

user_recipes = user_recipes.set_index('id')
recipe_db = recipe_db.set_index('id')

In [100]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

u_pref = pd.DataFrame({'id': ['usr_pref'],
                               'z1':  [0],
                               'z2':  [10],
                               'z3':  [0],
                               'z4':  [0],
                               'z5':  [0],
                               'z6':  [10],
                               'z7':  [0],
                               'z8':  [0],
                               'z9':  [0],
                               'z10': [0],
                               'z11': [10], 
                               'z12': [0]})
u_pref = u_pref.set_index('id')


recipe = pd.DataFrame({'id': ['usr_pref'],
                               'z1':  [0],
                               'z2':  [1],
                               'z3':  [0],
                               'z4':  [1],
                               'z5':  [0],
                               'z6':  [1],
                               'z7':  [0],
                               'z8':  [0],
                               'z9':  [1],
                               'z10': [0],
                               'z11': [1], 
                               'z12': [0]})
recipe = recipe.set_index('id')


# user_pref = pd.DataFrame(index=['user_pref'], columns=['z1', 'z2', 'z3', 'z4', 'z5', 'z6', 'z7', 'z8', 'z9', 'z10', 'z11', 'z12'])
# user_pref.loc['user_pref'] = user_recipes.sum()
# display(user_pref)

u_distance_array = cdist(u_pref, recipe, metric='euclidean')
# distance_array = cdist(user_pref.loc[['usr_pref']], recipe_db, metric='euclidean')

u_result_4 = pd.DataFrame(u_distance_array, columns=recipe.index.values, index=['u_distance_user_pref'])
# result_4 = pd.DataFrame(distance_array, columns=recipe_db.index.values, index=['distance_user_pref'])

u_result_4 = u_result_4.T.sort_values(by='u_distance_user_pref')
# result_4 = result_4.T.sort_values(by='distance_user_pref')
# display(result_4)

# result_4
u_result_4

          u_distance_user_pref
usr_pref             15.652476

In [105]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

u_pref = pd.DataFrame({'id': ['usr_pref'],
                               'z1':  [0],
                               'z2':  [1],
                               'z3':  [1],
                               'z4':  [1],
                               'z5':  [1],
                               'z6':  [1],
                               'z7':  [0],
                               'z8':  [1],
                               'z9':  [1],
                               'z10': [1],
                               'z11': [1], 
                               'z12': [1]})
u_pref = u_pref.set_index('id')

user_pref = pd.DataFrame(index=['user_pref'], columns=['z1', 'z2', 'z3', 'z4', 'z5', 'z6', 'z7', 'z8', 'z9', 'z10', 'z11', 'z12'])
user_pref.loc['user_pref'] = user_recipes.sum()
# display(user_pref)
u_distance_array = cdist(u_pref.loc[['usr_pref']], recipe_db, metric='euclidean')
distance_array = cdist(user_pref.loc[['user_pref']], recipe_db, metric='euclidean')

u_result_4 = pd.DataFrame(u_distance_array, columns=recipe_db.index.values, index=['u_distance_user_pref'])
result_4 = pd.DataFrame(distance_array, columns=recipe_db.index.values, index=['distance_user_pref'])

u_result_4 = u_result_4.T.sort_values(by='u_distance_user_pref')
result_4 = result_4.T.sort_values(by='distance_user_pref')
# display(result_4)

result_4
u_result_4
user_pref

     distance_user_pref
r5             8.124038
r2             8.660254
r4             8.660254
r3             8.774964
r10            8.774964
r1             8.944272
r6             9.327379
r8             9.380832
r9             9.486833
r7            10.099505

     u_distance_user_pref
r3               2.236068
r4               2.236068
r10              2.236068
r1               2.449490
r5               2.449490
r8               2.449490
r2               2.645751
r6               2.645751
r9               2.828427
r7               3.162278

           z1  z2  z3  z4  z5  z6  z7  z8  z9  z10  z11  z12
user_pref   0   4   6   1   5   4   0   1   1    2    1    1

In [88]:
import numpy as np
import pandas as pd
import scipy
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse
from scipy import spatial

user_recipes =  [ {'id': 'r1', 'z1': 0, 'z2': 0, 'z3': 1, 'z5': 1, 'z4':0, 'z6': 0, 'z7': 0, 'z8': 0, 'z9': 0, 'z10': 1, 'z11':1, 'z12': 0},
                  {'id': 'r2', 'z1': 0, 'z2': 1, 'z3': 1, 'z4': 0, 'z5':1, 'z6': 1, 'z7': 0, 'z8': 0, 'z9': 0, 'z10': 0, 'z11':0, 'z12': 0},
                 {'id': 'r3', 'z1': 0, 'z2': 1, 'z3': 1, 'z4': 0, 'z5':1, 'z6': 1, 'z7': 0, 'z8': 0, 'z9': 0, 'z10': 0, 'z11':0, 'z12': 0},
                 {'id': 'r4', 'z1': 0, 'z2': 1, 'z3': 1, 'z4': 0, 'z5':1, 'z6': 1, 'z7': 0, 'z8': 0, 'z9': 0, 'z10': 0, 'z11':0, 'z12': 0},
                 {'id': 'r5', 'z1': 0, 'z2': 1, 'z3': 1, 'z4': 0, 'z5':1, 'z6': 1, 'z7': 0, 'z8': 0, 'z9': 0, 'z10': 0, 'z11':0, 'z12': 0},
                  {'id': 'r6', 'z1': 0, 'z2': 0, 'z3': 1, 'z4': 0, 'z5':1, 'z6': 0, 'z7': 0, 'z8': 1, 'z9': 0, 'z10': 1, 'z11':0, 'z12': 0}]

#pd.DataFrame(user_recipes)
# user_recipes = pd.DataFrame(user_recipes)
# user_recipes = user_recipes.set_index(['id'])

# user_recipes = user_recipes.reindex(columns=sorted(user_recipes.columns))
# user_recipes
#user_recipes.columns.sort_values(ascending=1)
# user_recipes = user_recipes.sort_index(axis=0)
#user_recipes.sort_index(axis=1, inplace=True)
# user_recipes

# df = pd.DataFrame.from_dict(user_recipes, orient='index')
# df

In [188]:
import pandas as pd

data1 = {"a":[0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

data2 = {"a":[0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]}

df1 = pd.DataFrame(data1).T
df2 = pd.DataFrame(data2).T 

distance_array = cdist(df1, df2, metric='euclidean')

result_4 = pd.DataFrame(distance_array, index=['euclidiean'])
result_4 = result_4.T.sort_values(by='euclidiean')
result_4

   euclidiean
0         1.0

In [4]:
import pandas as pd

data1 = {"a":[0, 0, 1, 0, 0]}

data2 = {"a":[1, 0, 1, 0, 1]}

df1 = pd.DataFrame(data1).T
df2 = pd.DataFrame(data2).T 

distance_array = cdist(df1, df2, metric='jaccard')

result_4 = pd.DataFrame(distance_array, index=['jaccard'])
result_4 = result_4.T.sort_values(by='jaccard')
result_4

# j = p/p+q

    jaccard
0  0.666667

In [135]:
import pandas as pd

data1 = {"a":[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1]}

data2 = {"a":[1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0]}

df1 = pd.DataFrame(data1).T
df2 = pd.DataFrame(data2).T 

result_1 = pd.DataFrame()


user_recipes_subtracted = df1.sub(df2)
recipe = user_recipes_subtracted.abs().values.sum()
recipe

7

In [3]:
import pandas as pd

data1 = {"a":[0, 1, 0, 1]}

data2 = {"a":[1, 0, 0, 1]}

df1 = pd.DataFrame(data1).T
df2 = pd.DataFrame(data2).T 

distance_array = cdist(df1, df2, metric='euclidean')

result_4 = pd.DataFrame(distance_array, index=['euclidiean_user_pref'])
result_4 = result_4.T.sort_values(by='euclidiean_user_pref')
result_4

   euclidiean_user_pref
0              1.414214

In [61]:
from scipy.spatial.distance import squareform, pdist, cdist
??cdist()

3

1