In [122]:
from scipy.spatial.distance import cdist
import numpy as np

matr = np.random.randint(0, 3, size=(6, 8))

matr
cdist(matr[0:1], matr[1:], metric='cosine')

array([[0.42792245, 0.54773298, 0.36039785, 0.71573238, 0.21615048]])

In [46]:
from bson import json_util, ObjectId
from pandas.io.json import json_normalize
import json
import pymongo
import pandas as pd
from pymongo import MongoClient as Connection

connection = Connection()
db = connection.recipe_db
input_data = db.recipes_test_copy
#data = pd.DataFrame(list(input_data.find()))

data = json.loads(json_util.dumps(input_data.find()))
norm_data = json_normalize(data)

ingredients = json_normalize(data, record_path='ingredients', meta='id', record_prefix='ingredients_', errors='ignore' )
ingredients = pd.DataFrame(ingredients)

#schmeiss alle zutaten raus, die weniger als 4 mal verwendet werden
ingredients_unique = ingredients[ingredients.groupby('ingredients_id').ingredients_id.transform(len) > 4]

# drop duplicate by a column name
 
ingredients_unique.drop_duplicates(['ingredients_id'], keep='last')

ingredients_unique = ingredients_unique.drop(ingredients_unique.columns[[0, 3, 4]], axis=1)

ingredients_unique['ingredients_id'].value_counts()

16421    3393
4342     2371
4397     2272
16406    1863
16157    1585
6307     1505
2496     1296
6494     1152
1684      862
16317     859
0         843
16238     815
16396     691
2882      636
6305      633
16278     600
16215     557
1525      555
4432      514
5107      501
16407     482
4405      458
4409      457
4378      453
16403     445
16133     431
3103      429
7428      418
16404     406
16261     394
         ...
4589        5
2793        5
4490        5
4313        5
6746        5
12255       5
12070       5
1658        5
22575       5
388         5
3141        5
18129       5
1657        5
3704        5
16323       5
5051        5
2980        5
16416       5
16066       5
20627       5
16226       5
20595       5
20492       5
20748       5
21196       5
2873        5
11026       5
21117       5
2326        5
1767        5
Name: ingredients_id, Length: 797, dtype: int64

In [47]:
#schmeiss alle zutaten raus, die weniger als 4 mal verwendet werden
ingredients_trans = ingredients[ingredients.groupby('ingredients_id').ingredients_id.transform(len) > 4]

In [76]:
ingredients_trans

AttributeError: 'DataFrame' object has no attribute 'type'

In [89]:
v = ingredients_trans.pivot_table(
        index=['id'], 
         columns='ingredients_id', 
         values='ingredients_grams'
).reset_index()
v.index.name = v.columns.name = None

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [90]:
v.set_index('id', inplace=True)

In [93]:
id_list_five = [236609, 65896, 9023, 11758, 24264]
id_list_one = [16354]

test_df_one_recipe = v[v.index.isin(id_list_one)]

test_df_five_recipes = v[v.index.isin(id_list_five)]

test_df_five_recipes

from sklearn.metrics.pairwise import cosine_similarity



cosine_similarity(test_df_five_recipes, test_df_one_recipe)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [106]:
test_df_five_recipes = test_df_five_recipes.apply(pd.to_numeric)
test_df_five_recipes = test_df_five_recipes.fillna(0)
test_df_five_recipes

,0,111,126,257,388,443,445,578,615,629,...,24850,24865,25518,25522,26269,26706,26934,27343,27388,27805
id,,,,,,,,,,,,,,,,,,,,,
9023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11758,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24264,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65896,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
236609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [107]:


test_df_one_recipe = test_df_one_recipe.apply(pd.to_numeric)
test_df_one_recipe = test_df_one_recipe.fillna(0)

,0,111,126,257,388,443,445,578,615,629,...,24850,24865,25518,25522,26269,26706,26934,27343,27388,27805
id,,,,,,,,,,,,,,,,,,,,,
16354,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [119]:
test_df_five_recipes

,0,111,126,257,388,443,445,578,615,629,...,24850,24865,25518,25522,26269,26706,26934,27343,27388,27805
id,,,,,,,,,,,,,,,,,,,,,
9023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11758,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24264,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65896,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
236609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [121]:
from sklearn.metrics.pairwise import cosine_similarity




cosine_similarity(test_df_five_recipes, test_df_one_recipe)


9023	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0





11758	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
24264	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
65896	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
236609	0.0	0.0	0.0


array([[0.        ],
       [0.11785113],
       [0.55555556],
       [0.1490712 ],
       [0.13608276]])

SyntaxError: invalid syntax (<ipython-input-121-fd5414d018d5>, line 8)

In [110]:
test_df_one_recipe[(test_df_one_recipe > 0).any(axis=1)]

,0,111,126,257,388,443,445,578,615,629,...,24850,24865,25518,25522,26269,26706,26934,27343,27388,27805
id,,,,,,,,,,,,,,,,,,,,,
16354,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [112]:
statistics = test_df_one_recipe.describe()
# to describe all columns you can do this
statistics = test_df_one_recipe.describe()

#[column for column in statistics.columns if statistics.loc[][column] > 3]
# output ['name']

statistics

,0,111,126,257,388,443,445,578,615,629,...,24850,24865,25518,25522,26269,26706,26934,27343,27388,27805
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [123]:
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse


A_sparse = scipy.sparse.csr_matrix(test_df_one_recipe.values)
print(A_sparse)

  (0, 19)	13.5682821
  (0, 63)	54.0
  (0, 141)	340.5
  (0, 157)	39.9999962
  (0, 242)	55.0
  (0, 530)	122.0
  (0, 533)	25.0
  (0, 579)	15.4185019

In [120]:
A_sparse = scipy.sparse.csr_matrix(test_df_five_recipes.values)
print(A_sparse)

  (0, 20)	66.66667
  (0, 27)	5.33333349
  (0, 84)	9.856667
  (0, 130)	85.3333359
  (0, 232)	2.0
  (0, 398)	552.0
  (0, 558)	0.6
  (0, 566)	0.35
  (0, 581)	39.8333359
  (1, 202)	181.6
  (1, 242)	44.0
  (1, 353)	582.4
  (1, 514)	68.04
  (1, 516)	4.0
  (1, 517)	68.04
  (1, 528)	138.0
  (1, 677)	181.6
  (2, 19)	9.243697
  (2, 157)	120.0
  (2, 202)	302.6667
  (2, 242)	27.8666668
  (2, 252)	24.833334
  (2, 557)	0.9255556
  (2, 566)	0.6666667
  (2, 579)	3.426334
  (2, 580)	0.266666681
  (3, 19)	36.6666679
  (3, 382)	78.3333359
  (3, 392)	472.0
  (3, 412)	22.6666679
  (3, 500)	224.0
  (4, 15)	112.999992
  (4, 130)	128.0
  (4, 157)	120.0
  (4, 232)	9.0
  (4, 397)	456.0
  (4, 544)	1.4

In [99]:
test_df_one_recipe.apply(pd.to_numeric)

,0,111,126,257,388,443,445,578,615,629,...,24850,24865,25518,25522,26269,26706,26934,27343,27388,27805
id,,,,,,,,,,,,,,,,,,,,,
16354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
v

,0,111,126,257,388,443,445,578,615,629,...,24850,24865,25518,25522,26269,26706,26934,27343,27388,27805
id,,,,,,,,,,,,,,,,,,,,,
6806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8493,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8498,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8508,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8526,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8533,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246867,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254325,NaN,NaN,NaN,NaN,NaN,NaN,113.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254417,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255263,NaN,0.166667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256535,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256864,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259870,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261325,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263611,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
#v.fillna(0)

,id,0,111,126,257,388,443,445,578,615,...,24850,24865,25518,25522,26269,26706,26934,27343,27388,27805
0,6806,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,6900,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7198,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,8493,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8494,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,8495,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,8496,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8497,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,8498,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,8500,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,8501,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,8502,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,8503,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,8504,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,8506,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,8508,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,8509,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,8515,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,8517,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,8519,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,8522,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,8523,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,8524,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,8525,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,8526,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,8527,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,8528,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,8529,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,8532,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,8533,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6275,246867,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6276,247066,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6277,253157,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6278,254325,0.0,0.000000,0.0,0.0,0.0,0.0,113.5,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6279,254417,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6280,254692,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6281,254812,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6282,254874,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6283,254940,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6284,255038,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6285,255263,0.0,0.166667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6286,255545,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6287,255936,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6288,256535,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6289,256864,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6290,257054,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6291,257312,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6292,257600,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6293,257938,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6294,258468,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6295,258878,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6296,259870,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6297,260193,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6298,261124,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6299,261325,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6300,261608,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6301,263611,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6302,263744,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6303,263799,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6304,263813,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [84]:
v.get_dtype_counts

<bound method NDFrame.get_dtype_counts of           id    0       111  126  257  388  443    445  578  615  ...    \
0       6806  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
1       6900  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
2       7198  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
3       8493  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
4       8494  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
5       8495  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6       8496  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
7       8497  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
8       8498  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
9       8500  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
10      8501  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
11      8502  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
12      8503  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
13      8504  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
14      8506  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
15      8508  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
16      8509  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
17      8515  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
18      8517  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
19      8519  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
20      8522  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
21      8523  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
22      8524  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
23      8525  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
24      8526  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
25      8527  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
26      8528  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
27      8529  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
28      8532  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
29      8533  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
...      ...  ...       ...  ...  ...  ...  ...    ...  ...  ...  ...
6275  246867  0.0       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6276  247066  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6277  253157  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6278  254325  NaN       NaN  NaN  NaN  NaN  NaN  113.5  NaN  NaN  ...
6279  254417  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6280  254692  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6281  254812  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6282  254874  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6283  254940  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6284  255038  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6285  255263  NaN  0.166667  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6286  255545  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6287  255936  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6288  256535  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6289  256864  0.0       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6290  257054  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6291  257312  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6292  257600  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6293  257938  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6294  258468  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6295  258878  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6296  259870  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6297  260193  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6298  261124  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6299  261325  0.0       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6300  261608  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6301  263611  0.0       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6302  263744  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6303  263799  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...
6304  263813  NaN       NaN  NaN  NaN  NaN  NaN    NaN  NaN  NaN  ...

      24850  24865  25518  25522  26269  26706  26934  27343  27388  27805
0       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
1       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
3       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
4       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
5       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
7       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
8       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
9       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
10      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
11      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
12      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
13      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
14      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
15      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
16      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
17      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
18      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
19      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
20      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
21      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
22      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
23      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
24      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
25      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
26      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
27      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
28      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
29      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
6275    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6276    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6277    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6278    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6279    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6280    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6281    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6282    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6283    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6284    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6285    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6286    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6287    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6288    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6289    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6290    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6291    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6292    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6293    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6294    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6295    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6296    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6297    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6298    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6299    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6300    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6301    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6302    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6303    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
6304    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN

[6305 rows x 798 columns]>

In [ ]:
print(ingredients_trans.loc[ingredients_trans['id'] == 59661 && ])

In [56]:
ingredients_trans.loc[ingredients_trans['id'] == 59661 && ingredients_trans['ingredients_id'] == 16157, 'ingredients_grams'].iloc[0]

SyntaxError: invalid syntax (<ipython-input-56-5dcbff8d2066>, line 1)

In [58]:
ingredients_trans['ingredients_grams'].loc[ingredients_trans['id'] == 59661][ingredients_trans['ingredients_id'] == 16157]

0    11.36
Name: ingredients_grams, dtype: float64

In [72]:
df_test = pd.crosstab(ingredients_trans.id, ingredients_trans.ingredients_trans)

AttributeError: 'DataFrame' object has no attribute 'ingredients_trans'

In [77]:
ingredients_trans

,ingredients_grams,ingredients_id,ingredients_name,ingredients_type,id
0,11.360000,16157,10 g butter,Normal,59661
1,41.800000,4405,40 g sliced green onions,Normal,59661
2,4.800000,4342,"1-1/2 cloves garlic, minced",Normal,59661
3,227.200000,4520,3/4 (10 ounce) package frozen chopped spinach ...,Normal,59661
4,182.400009,16243,180 g ricotta cheese,Normal,59661
5,92.000000,16261,90 g sour cream,Normal,59661
6,180.800000,16231,180 g shredded Monterey Jack cheese,Normal,59661
7,208.000000,2351,8 (6 inch) corn tortillas,Normal,59661
8,425.600000,7431,3/4 (19 ounce) can enchilada sauce,Normal,59661
9,302.666700,3103,305 g ground beef,Normal,16330
10,61.666668,1650,60 g uncooked long grain white rice,Normal,16330
11,158.000000,2496,160 ml water,Normal,16330
12,476.000000,4432,4 green bell peppers,Normal,16330
13,298.666700,4582,1-1/4 (8 ounce) cans tomato sauce,Normal,16330
14,11.333334,7428,10 ml Worcestershire sauce,Normal,16330
15,0.462778,16396,0.5 g garlic powder,Normal,16330
16,0.350000,16402,0.4 g onion powder,Normal,16330
17,1.000000,16421,salt and pepper to taste,HideAmounts,16330
18,1.000000,20245,1 g Italian seasoning,Normal,16330
19,0.133000,10536,cooking spray,HideAmounts,235151
20,456.000000,6522,4 bone-in chicken thighs with skin,Normal,235151
21,0.687500,18740,0.7 g garlic salt,Normal,235151
22,0.687500,18739,0.6 ml onion salt,Normal,235151
23,0.187500,16403,0.2 g dried oregano,Normal,235151
24,0.179167,16417,0.2 g ground thyme,Normal,235151
25,0.285104,16404,0.3 g paprika,Normal,235151
26,0.262500,16406,0.3 g ground black pepper,Normal,235151
27,472.000000,6494,"4 skinless, boneless chicken breast halves",Normal,240208
28,27.000000,6307,30 ml olive oil,Normal,240208
29,16.500000,18752,15 g coarse sea salt,Normal,240208
...,...,...,...,...,...
61169,1.050000,20551,1 g ground cumin,Normal,236032
61170,0.550000,16418,0.6 g ground turmeric,Normal,236032
61171,5.000000,7818,5 ml Asian chile pepper sauce (such as sambal ...,Normal,236032
61172,6.660793,2112,7 g dry bread crumbs,Normal,236032
61173,10.600000,2882,10 ml soy sauce,Normal,236032
61174,454.000000,10643,455 g ground chicken,Normal,236032
61175,5.300000,16159,5 g chopped fresh basil,Normal,236032
61176,0.400000,16421,salt,HideAmounts,236032
61177,0.200000,16407,"1 pinch cayenne pepper, or to taste",Normal,236032
61178,11.500000,3717,10 g cilantro leaves,Normal,236032
61179,172.000000,2339,4 hamburger buns,Normal,236032
61180,123.333336,1650,125 g uncooked long-grain rice,Normal,245877
61181,302.933350,6494,"305 g boneless skinless chicken breasts, cut i...",Normal,245877
61182,1.933333,22575,2 g Jamaican jerk seasoning blend,Normal,245877
61183,9.083334,6305,10 ml vegetable oil,Normal,245877
61184,73.333336,4397,"5/8 medium onion, diced",Normal,245877
61185,373.333344,22117,"5/8 (20 ounce) can pineapple chunks, drained",Normal,245877
61186,283.333344,2779,"5/8 (15 ounce) can black beans, drained and ri...",Normal,245877
61187,85.333336,4431,5/8 (4.5 ounce) can chopped green chilies,Normal,245877
61189,14.000000,23337,15 g dried chipotle chile pepper,Normal,244188
61190,14.200000,3724,15 g dried ancho chile pepper,Normal,244188
61191,59.250000,2496,60 ml water,Normal,244188
61192,27.500000,20269,"1/4 red onion, cut into small chunks",Normal,244188
61193,6.000000,4342,2 cloves garlic,Normal,244188
61194,5.500000,18752,6 g sea salt,Normal,244188
61195,1.050000,20551,1 g ground cumin,Normal,244188
61196,0.750000,16403,0.8 g dried oregano,Normal,244188
61197,1.050000,16406,1 g freshly ground black pepper,Normal,244188
61198,13.500000,6307,15 ml olive oil,Normal,244188
61199,567.500000,6527,"570 g skinless, boneless chicken thighs",Normal,244188

In [23]:
test2.index.values

array([  7025,   7034,   7915,   8626,   8652,   8665,   8691,   8694,
         8847,   8887,   9066,   9069,   9075,   9111,   9125,   9169,
         9174,   9183,   9184,   9204,   9209,   9219,   9228,   9237,
         9344,   9358,   9372,   9376,   9377,   9456,   9501,   9560,
         9615,  10462,  11669,  11679,  11691,  11692,  11696,  11698,
        11723,  11727,  11752,  11760,  11771,  11776,  11786,  11802,
        11805,  11839,  11861,  11865,  11883,  11899,  11903,  11925,
        11933,  11966,  11967,  12009,  12042,  12074,  12245,  12347,
        12384,  12720,  12899,  12907,  12960,  12965,  12991,  12996,
        12999,  13043,  13059,  13113,  13163,  13410,  13482,  13489,
        13506,  13509,  13517,  13524,  13590,  13606,  13608,  13632,
        13637,  13799,  13827,  13829,  13839,  13852,  13881,  13884,
        13890,  13893,  13894,  13896,  13897,  13900,  13901,  13903,
        13905,  13907,  13911,  13913,  13914,  13916,  13925,  13930,
        13933,  13937,  13938,  13940,  13941,  13948,  13949,  13953,
        13954,  13961,  13963,  13974,  13977,  13981,  13982,  13988,
        13989,  13996,  13999,  14015,  14018,  14019,  14023,  14033,
        14035,  14041,  14048,  14050,  14056,  14064,  14069,  14081,
        14086,  14087,  14088,  14090,  14091,  14095,  14102,  14105,
        14110,  14112,  14113,  14120,  14132,  14134,  14136,  14138,
        14140,  14144,  14151,  14152,  14157,  14158,  14159,  14169,
        14180,  14184,  14209,  14223,  14224,  14228,  14229,  14237,
        14238,  14259,  14260,  14297,  14304,  14339,  14341,  14363,
        14368,  14381,  14406,  14419,  14438,  14440,  14469,  14497,
        14504,  14506,  14512,  14522,  14581,  14595,  14811,  14814,
        14817,  14830,  14831,  14837,  14838,  14859,  14860,  14861,
        14873,  14922,  14927,  14930,  14970,  15006,  15013,  15022,
        15025,  15084,  15109,  15141,  15176,  15179,  15340,  15359,
        15417,  15436,  15501,  15559,  15607,  15611,  15618,  15746,
        15998,  16015,  16085,  16110,  16135,  16217,  16239,  16259,
        16330,  16352,  16408,  16409,  16457,  16482,  16488,  16492,
        16495,  16505,  16506,  16508,  16540,  16542,  16557,  16604,
        16625,  16641,  16659,  16662,  16664,  16667,  16683,  16700,
        16715,  16717,  16756,  16760,  16765,  16779,  16789,  16796,
        16881,  16907,  16926,  16939,  17033,  17069,  17071,  17127,
        17130,  17227,  17323,  17351,  17435,  17437,  17445,  17500,
        17522,  17535,  17596,  17717,  17960,  17971,  18003,  18034,
        18040,  18045,  18057,  18061,  18077,  18088,  18100,  18213,
        18217,  18219,  18241,  18249,  18254,  18256,  18266,  18269,
        18271,  18274,  18284,  18288,  18292,  18293,  18313,  18318,
        18324,  18379,  18391,  18392,  18411,  18412,  18414,  18417,
        18438,  18450,  18465,  18498,  18509,  18517,  18533,  18805,
        18809,  18819,  18996,  19000,  19023,  19044,  19211,  19306,
        19368,  19375,  19388,  19389,  19402,  19422,  19423,  19427,
        19541,  19576,  19583,  19584,  19587,  19591,  19670,  19687,
        19770,  19772,  19841,  19850,  19854,  19855,  19858,  19888,
        19919,  19921,  20034,  20082,  20293,  20312,  20320,  20340,
        20350,  20366,  20462,  20471,  20548,  20569,  20577,  20645,
        20669,  20672,  20690,  20724,  20730,  20749,  20785,  20793,
        20797,  20808,  20846,  20859,  20867,  20876,  20920,  20963,
        20968,  20976,  21000,  21009,  21013,  21021,  21060,  21066,
        21070,  21080,  21083,  21092,  21114,  21126,  21127,  21132,
        21134,  21160,  21165,  21166,  21174,  21176,  21190,  21209,
        21220,  21277,  21315,  21353,  21391,  21455,  21518,  21532,
        21574,  21587,  21643,  21694,  21740,  21744,  21745,  21757,
        21844,  22161,  22163,  22176,  22200,  22246,  22248,  22271,
        22283,  22304,  22308,  22314,  22415,  22448,  22450,  22491,
        22494,  22539,  22617,  22633,  22653,  22657,  22659,  22718,
        22729,  22742,  22765,  22919,  22924,  22936,  22950,  22960,
        22976,  22986,  23081,  23124,  23176,  23252,  23256,  23262,
        23395,  23421,  23444,  23445,  23539,  23591,  23597,  23620,
        23724,  23781,  23783,  23860,  23929,  23953,  23982,  23988,
        24015,  24043,  24056,  24148,  24180,  24182,  24191,  24192,
        24243,  24246,  24291,  24321,  24329,  24368,  24370,  24372,
        24379,  24380,  24382,  24415,  24578,  24610,  24616,  24626,
        24634,  24712,  24717,  24720,  24724,  24738,  24768,  24771,
        24772,  24773,  24775,  24808,  24867,  24872,  25075,  25156,
        25160,  25237,  25239,  25241,  25248,  25267,  25272,  25273,
        25274,  25285,  25289,  25309,  25311,  25312,  25314,  25317,
        25320,  25321,  25331,  25333,  25335,  25338,  25339,  25343,
        25345,  25346,  25474,  25477,  25528,  25529,  25657,  25690,
        25691,  25767,  25887,  25889,  25894,  25900,  25908,  25910,
        25911,  25916,  25920,  25922,  26249,  26257,  26297,  26301,
        26391,  26490,  26498,  26540,  26699,  26700,  26707,  26740,
        26787,  26788,  26806,  26819,  26823,  26835,  26857,  26921,
        26942,  26972,  27055,  27070,  27192,  29112,  29915,  29940,
        29945,  29949,  31519,  33118,  33160,  33474,  34689,  34946,
        35157,  35304,  35393,  36497,  36922,  36925,  38277,  38818,
        40204,  40448,  40573,  41596,  41638,  41998,  42022,  42165,
        42688,  42864,  42911,  42936,  43742,  43789,  43805,  43926,
        44921,  45394,  45446,  45688,  45736,  45954,  46028,  46136,
        46372,  46462,  46647,  46876,  46887,  46960,  47247,  47472,
        47564,  47613,  47635,  47898,  48032,  48156,  49262,  49280,
        49350,  49353,  49534,  49923,  50030,  50096,  50501,  51025,
        51156,  51283,  52232,  52934,  53462,  53518,  53560,  54143,
        54165,  54675,  55207,  55352,  55451,  55641,  56136,  56161,
        56659,  56737,  56933,  57124,  57899,  58165,  58246,  58645,
        58854,  59467,  59661,  59671,  59853,  59967,  60598,  60923,
        60924,  62594,  62686,  62761,  63250,  64116,  64513,  64816,
        65066,  65104,  65300,  65442,  66646,  67132,  68436,  68530,
        68532,  68537,  68540,  69027,  69471,  69635,  69795,  69879,
        69999,  70037,  70101,  70312,  70330,  71141,  71574,  72616,
        72683,  72689,  72712,  72876,  72878,  73047,  73090,  73139,
        73208,  73297,  73456,  73470,  73594,  73691,  73737,  73748,
        73975,  74007,  74077,  74350,  74437,  74591,  75408,  75595,
        76137,  76283,  76297,  76697,  76955,  77215,  77522,  78052,
        78370,  79450,  80677,  80743,  80974,  81062,  81108,  81441,
        81548,  82078,  82503,  82575,  83087,  83307,  83576,  83637,
        83716,  83992,  84043,  84450,  84851,  84863,  85452,  85598,
        85881,  86197,  86229,  86241,  86310,  86313,  86390,  86446,
        86514,  86515,  86577,  86808,  86925,  87068,  87075,  87201,
        87271,  87365,  87563,  87590,  87678,  87694,  87822,  87848,
        88278,  88583,  88768,  89033,  89195,  89334,  89452,  89682,
        89982,  90044,  90105,  90315,  91679,  93896,  95860,  96431,
        96563,  99244, 100690, 103915, 104850, 104947, 105039, 105540,
       105581, 109683, 109914, 111515, 115746, 126942, 132280, 132394,
       132785, 135534, 139722, 139977, 141678, 142179, 142481, 143082,
       143276, 144988, 145549, 145672, 146022, 146065, 146824, 147142,
       148509, 149218, 149398, 149448, 150135, 150166, 152175, 152418,
       152931, 152937, 152938, 153848, 155074, 155357, 155534, 155552,
       158833, 158899, 161118, 161685, 162501, 165500, 165649, 165783,
       166067, 166485, 166611, 167163, 168881, 169278, 173730, 174343,
       178095, 180735, 186378, 188690, 191885, 198255, 198617, 200254,
       200877, 200919, 201097, 201845, 205611, 205651, 209691, 213042,
       214048, 214650, 214756, 214921, 215030, 215073, 215093, 215311,
       215633, 216051, 216190, 216717, 216950, 217002, 217065, 217109,
       217330, 217829, 217913, 217947, 217951, 218207, 218288, 218542,
       218604, 218648, 219160, 220192, 220477, 220479, 220642, 220661,
       220827, 221293, 222006, 222247, 222801, 223042, 223313, 223354,
       228337, 228584, 229241, 230050, 230658, 230870, 231514, 231616,
       231619, 232210, 232908, 232967, 233146, 234324, 235151, 235259,
       236564, 241709, 244605, 244779, 244973, 246803, 247381, 254691,
       254692, 254940, 254971, 255695, 256014, 256728, 257695, 261124,
       261608, 261823])

In [49]:
test2 = pd.get_dummies(ingredients_trans['ingredients_id']).groupby(ingredients_trans['id']).apply(max)

In [54]:
#df = test2.set_index(['id'])
#id_list = [236609, 65896, 9023, 11758, 24264]
id_list = [16354]
#de = test2.iloc[id_list]
#test id = 16354
#7025

test_df_one_recipe = test2[test2.index.isin(id_list)]

test_df_five_recipes = test2[test2.index.isin(id_list)]

In [55]:
test_df_one_recipe

,0,111,126,257,388,443,445,578,615,629,...,24850,24865,25518,25522,26269,26706,26934,27343,27388,27805
id,,,,,,,,,,,,,,,,,,,,,
16354,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [53]:
test_df_fice_recipes

,0,111,126,257,388,443,445,578,615,629,...,24850,24865,25518,25522,26269,26706,26934,27343,27388,27805
id,,,,,,,,,,,,,,,,,,,,,
9023,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11758,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24264,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
65896,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
236609,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [59]:
test_df_fice_recipes[0] > 0

id
9023      False
11758     False
24264     False
65896     False
236609    False
Name: 0, dtype: bool

In [70]:
data = {'zutaten_id': [5, 8, 3, 6, 2], 'rezept_id': [1, 1, 2, 2, 3]}
df = pd.DataFrame(data)

In [68]:
df

   zutaten_id  rezept_id
0           5          1
1           8          1
2           3          2
3           6          2
4           2          3

In [71]:
df.set_index('rezept_id',inplace=True)
df

           zutaten_id
rezept_id
1                   5
1                   8
2                   3
2                   6
3                   2

In [41]:
de

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [ ]:
df.ix[(df.index.hour == 3)

In [30]:
#.loc[test2['id'].isin([7025,7034])]
test2

,0,111,126,1416,1502,1507,1525,1526,1527,1536,...,20453,20466,20473,20482,20496,20551,20699,20726,22106,23274
id,,,,,,,,,,,,,,,,,,,,,
7025,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7034,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7915,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8626,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8652,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8665,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8691,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
8694,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8847,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8887,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9066,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9069,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9075,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9111,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9125,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9169,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9174,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9183,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9184,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9204,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9209,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9219,1,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9228,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9237,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9344,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9358,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9372,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9376,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9377,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9456,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230658,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
230870,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
231514,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
231616,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
231619,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
232210,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
232908,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
232967,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
233146,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
234324,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
235151,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
235259,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
236564,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
241709,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
244605,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
244779,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
244973,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
246803,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
247381,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
254691,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
254692,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
254940,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
254971,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
255695,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
256014,1,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
256728,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
257695,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
261124,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
261608,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
261823,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [16]:
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse

df=pd.DataFrame(test2)
A_sparse = scipy.sparse.csr_matrix(df.values)

similarities = cosine_similarity(A_sparse)
print('pairwise dense output:\n {}\n'.format(similarities))

#also can output sparse matrices
similarities_sparse = cosine_similarity(A_sparse,dense_output=False)
print('pairwise sparse output:\n {}\n'.format(similarities_sparse))

pairwise dense output:
 [[1.         0.71428571 0.25197632 ... 0.11952286 0.12598816 0.        ]
 [0.71428571 1.         0.12598816 ... 0.11952286 0.12598816 0.11952286]
 [0.25197632 0.12598816 1.         ... 0.10540926 0.11111111 0.        ]
 ...
 [0.11952286 0.11952286 0.10540926 ... 1.         0.42163702 0.2       ]
 [0.12598816 0.12598816 0.11111111 ... 0.42163702 1.         0.10540926]
 [0.         0.11952286 0.         ... 0.2        0.10540926 1.        ]]

pairwise sparse output:
   (0, 984)	0.1259881576697424
  (0, 983)	0.11952286093343936
  (0, 982)	0.08451542547285165
  (0, 977)	0.1690308509457033
  (0, 976)	0.0890870806374748
  (0, 975)	0.1259881576697424
  (0, 973)	0.13363062095621217
  (0, 972)	0.1259881576697424
  (0, 963)	0.1259881576697424
  (0, 962)	0.10482848367219183
  (0, 958)	0.1259881576697424
  (0, 956)	0.1690308509457033
  (0, 952)	0.1889822365046136
  (0, 945)	0.11952286093343936
  (0, 942)	0.14285714285714282
  (0, 940)	0.1091089451179962
  (0, 937)	0.10482848367219183
  (0, 933)	0.14285714285714282
  (0, 928)	0.1091089451179962
  (0, 926)	0.1543033499620919
  (0, 921)	0.1690308509457033
  (0, 920)	0.13363062095621217
  (0, 919)	0.07881104062391006
  (0, 918)	0.14285714285714282
  (0, 917)	0.1259881576697424
  :	:
  (985, 97)	0.3651483716701108
  (985, 76)	0.1825741858350554
  (985, 73)	0.2
  (985, 72)	0.2860387767736777
  (985, 71)	0.2860387767736777
  (985, 69)	0.3872983346207417
  (985, 68)	0.3265986323710904
  (985, 67)	0.23904572186687872
  (985, 66)	0.253546276418555
  (985, 56)	0.11952286093343936
  (985, 52)	0.33541019662496846
  (985, 29)	0.4216370213557839
  (985, 985)	0.9999999999999999
  (985, 916)	0.25819888974716115
  (985, 873)	0.31622776601683794
  (985, 868)	0.19069251784911848
  (985, 857)	0.2
  (985, 787)	0.42257712736425834
  (985, 782)	0.33541019662496846
  (985, 655)	0.27386127875258315
  (985, 624)	0.30000000000000004
  (985, 390)	0.47809144373375745
  (985, 245)	0.3872983346207417
  (985, 229)	0.1825741858350554
  (985, 179)	0.27386127875258315

array([[1.        , 0.71428571, 0.25197632, ..., 0.11952286, 0.12598816,
        0.        ],
       [0.71428571, 1.        , 0.12598816, ..., 0.11952286, 0.12598816,
        0.11952286],
       [0.25197632, 0.12598816, 1.        , ..., 0.10540926, 0.11111111,
        0.        ],
       ...,
       [0.11952286, 0.11952286, 0.10540926, ..., 1.        , 0.42163702,
        0.2       ],
       [0.12598816, 0.12598816, 0.11111111, ..., 0.42163702, 1.        ,
        0.10540926],
       [0.        , 0.11952286, 0.        , ..., 0.2       , 0.10540926,
        1.        ]])

In [11]:
import scipy
sparse_mat = scipy.sparse.coo_matrix((t.values, (ingredients_trans['ingredients_id'], ingredients_trans['id'])))

NameError: name 't' is not defined

In [13]:
scipy.sparse.csr_matrix(df.values)

<986x258 sparse matrix of type '<class 'numpy.uint8'>'
	with 7874 stored elements in Compressed Sparse Row format>